const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const state={token:sessionStorage.getItem('appgog-install-token')||'',panel:'bt',session:null,config:null,summary:null};
const screens=['auth','check','config','review','deploy'];
function show(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));$$('#steps li').forEach((x,index)=>{const current=screens.indexOf(name),own=screens.indexOf(x.dataset.step);x.classList.toggle('active',own===current);x.classList.toggle('done',own<current)});scrollTo({top:0,behavior:'smooth'})}
function notice(message=''){const node=$('#notice');node.hidden=!message;node.textContent=message}
async function api(path,options={}){const response=await fetch(`/install/api/${path}`,{...options,headers:{'content-type':'application/json','authorization':`Bearer ${state.token}`,...options.headers}});const data=await response.json().catch(()=>({error:'安装服务返回了无效响应'}));if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data}
function badge(text,kind='neutral'){const node=$('#connectionBadge');node.textContent=text;node.className=`status ${kind}`}
function renderChecks(data){state.session=data;const list=$('#checkList');list.replaceChildren(...data.preflight.checks.map(check=>{const li=document.createElement('li');if(!check.ok)li.className='fail';li.innerHTML=`<span>${check.ok?'✓':'!'}</span><div><strong></strong><small></small></div>`;li.querySelector('strong').textContent=check.label;li.querySelector('small').textContent=check.detail;return li}));$('#checkSummary').textContent=data.preflight.ok?'所有必需项目均已通过。':'仍有项目未通过，请在面板中修复后重试。';$('#checkNext').disabled=!data.preflight.ok;if(data.preflight.dryRun)$('#checkSummary').textContent+=' 当前为安全演示模式。'}
async function connect(){notice();const data=await api('session');badge(data.installed?'已完成安装':'Token 已验证',data.installed?'good':'good');$('#forgetToken').hidden=false;renderChecks(data);if(data.installed){show('deploy');complete(data.state);return}show(data.configured?'deploy':'check')}
$('#tokenForm').addEventListener('submit',async event=>{event.preventDefault();state.token=$('#installToken').value.trim();sessionStorage.setItem('appgog-install-token',state.token);try{await connect()}catch(error){sessionStorage.removeItem('appgog-install-token');state.token='';badge('连接失败','bad');notice(error.message)}});
$('#toggleToken').addEventListener('click',()=>{const field=$('#installToken');field.type=field.type==='password'?'text':'password';$('#toggleToken').textContent=field.type==='password'?'显示':'隐藏'});
$('#forgetToken').addEventListener('click',()=>{sessionStorage.removeItem('appgog-install-token');state.token='';location.reload()});
$$('[data-back]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.back)));
$$('.panel-card').forEach(button=>button.addEventListener('click',()=>{state.panel=button.dataset.panel;$$('.panel-card').forEach(card=>{const active=card===button;card.classList.toggle('selected',active);card.setAttribute('aria-checked',String(active))})}));
$('#refreshChecks').addEventListener('click',async()=>{try{renderChecks(await api('session'))}catch(error){notice(error.message)}});
$('#checkNext').addEventListener('click',()=>show('config'));
$('#externalAi').addEventListener('change',event=>{$('#aiFields').hidden=!event.target.checked});
function formConfig(){const form=new FormData($('#configForm'));return{panel:state.panel,origin:form.get('origin'),webPort:Number(form.get('webPort')),adminEmail:form.get('adminEmail'),adminDisplayName:form.get('adminDisplayName'),adminPassword:form.get('adminPassword'),xboard:{login:form.get('xLogin'),register:form.get('xRegister'),purchase:form.get('xPurchase'),dashboard:form.get('xDashboard'),ticket:form.get('xTicket'),affiliate:form.get('xAffiliate')},externalAi:form.get('externalAi')==='on',aiBaseUrl:form.get('aiBaseUrl'),aiKey:form.get('aiKey')}}
const panelNames={bt:'宝塔面板','1panel':'1Panel',aapanel:'aaPanel',docker:'Docker',ssh:'SSH'};
function review(config){const links=Object.values(config.xboard).filter(Boolean).length;const items=[['部署方式',panelNames[config.panel]],['站点',config.origin],['Web 端口',config.webPort],['API 端口','3000（固定）'],['管理员',config.adminEmail],['Xboard 跳转',`${links} 项普通 URL`],['外部 AI',config.externalAi?'显式启用':'保持关闭'],['密钥','服务器自动生成']];const card=$('#reviewCard');card.replaceChildren(...items.map(([label,value])=>{const item=document.createElement('div');item.className='review-item';const a=document.createElement('span'),b=document.createElement('strong');a.textContent=label;b.textContent=value;item.append(a,b);return item}));show('review')}
$('#configForm').addEventListener('submit',event=>{event.preventDefault();notice();state.config=formConfig();review(state.config)});
$('#confirmIsolation').addEventListener('change',event=>{$('#saveConfig').disabled=!event.target.checked});
$('#saveConfig').addEventListener('click',async()=>{notice();const button=$('#saveConfig');button.disabled=true;button.textContent='正在安全写入…';try{const result=await api('configure',{method:'POST',body:JSON.stringify(state.config)});state.summary=result.summary;state.config.adminPassword='';state.config.aiKey='';show('deploy')}catch(error){notice(error.message);button.disabled=false}finally{button.textContent='保存安全配置'}});
function renderDeploy(results=[]){const list=$('#deployLog');list.replaceChildren(...results.map(result=>{const li=document.createElement('li');li.className=result.ok?'ok':'fail';const strong=document.createElement('strong');strong.textContent=result.name;li.append(strong);if(result.output){const pre=document.createElement('pre');pre.textContent=result.output;li.append(pre)}return li}))}
function complete(saved={}){$('#deployTitle').textContent='安装完成。';$('#deployLead').textContent='服务已通过健康检查，安装入口已经永久锁定。';$('#deployButton').hidden=true;$('#deployOrb').classList.remove('running');$('#completeCard').hidden=false;const links=$('#completeLinks');links.replaceChildren();const origin=saved?.origin||state.summary?.origin;if(origin){const site=document.createElement('a');site.href=origin;site.textContent='打开 APPGOG';site.target='_blank';site.rel='noopener noreferrer';links.append(site)}const admin=document.createElement('a');admin.href=origin?`${origin}/admin`:'/admin';admin.textContent='打开管理后台';admin.target='_blank';admin.rel='noopener noreferrer';links.append(admin)}
$('#deployButton').addEventListener('click',async()=>{notice();const button=$('#deployButton');button.disabled=true;button.textContent='安装进行中…';$('#deployOrb').classList.add('running');renderDeploy([{name:'正在执行固定部署流程',ok:true,output:'请勿关闭此页面。首次构建可能需要数分钟。'}]);try{const result=await api('deploy',{method:'POST',body:'{}'});renderDeploy(result.results);complete(state.summary)}catch(error){notice(error.message);$('#deployOrb').classList.remove('running');button.disabled=false;button.textContent='重新执行安装'}});
if(state.token){$('#installToken').value=state.token;connect().catch(error=>{notice(error.message);sessionStorage.removeItem('appgog-install-token');state.token=''})}
