import {describe,it,expect,vi} from 'vitest';
import {aiSources,aiTicketUrl,createAiSearch} from './ai-client';
describe('shared AI component request lifecycle',()=>{
  const response={answer:'说明',mode:'answer',unresolved:false,sourceIds:[],sources:[{id:'a',title:'安装',slug:'help/install',url:'https://evil.invalid'}],ticketUrl:'https://panel.example.invalid/ticket'};
  it('rebuilds source URLs and rejects credential-bearing outbound URLs',()=>{expect(aiSources([...response.sources,...response.sources,{id:'b',title:'x',slug:'../secret'}])).toEqual([{id:'a',title:'安装',slug:'help/install',url:'/content/help/install',excerpt:''}]);for(const value of ['//evil.invalid','https://x.invalid/?token=x','https://x.invalid/#x','https://a:b@x.invalid','javascript:x'])expect(aiTicketUrl(value)).toBe('')});
  it('validates and normalizes question without sending empty/overlong input',async()=>{const transport=vi.fn(async(_question:string,_signal:AbortSignal)=>response),state=createAiSearch(transport);await state.ask();state.question.value='x'.repeat(2001);await state.ask();expect(transport).not.toHaveBeenCalled();state.question.value=' Ｗindows ';await state.ask();expect(transport.mock.calls[0][0]).toBe('Windows');expect(state.result.value?.sources[0].url).toBe('/content/help/install')});
  it('ignores old responses after newer questions and clear',async()=>{const resolvers:((value:any)=>void)[]=[],signals:AbortSignal[]=[];const state=createAiSearch((_q,signal)=>{signals.push(signal);return new Promise(resolve=>resolvers.push(resolve))});state.question.value='旧问题';const first=state.ask();state.question.value='新问题';const second=state.ask();expect(signals[0].aborted).toBe(true);resolvers[1]({...response,answer:'新答案'});await second;resolvers[0]({...response,answer:'旧答案'});await first;expect(state.result.value?.answer).toBe('新答案');state.clear();expect(state.result.value).toBeNull();expect(state.question.value).toBe('')});
  it('cancels pending waits and never surfaces raw upstream secrets',async()=>{let finish:(value:any)=>void=()=>{};const state=createAiSearch(()=>new Promise(resolve=>{finish=resolve}));state.question.value='安装';const pending=state.ask();state.cancel();finish(response);await pending;expect(state.result.value).toBeNull();expect(state.loading.value).toBe(false);const broken=createAiSearch(async()=>{throw {message:'sk-secret',response:{status:429}}});broken.question.value='安装';await broken.ask();expect(broken.error.value).toContain('频繁');expect(broken.error.value).not.toContain('sk-secret')});
  it('reports malformed result safely and accepts explicit document fallback',async()=>{const state=createAiSearch(async()=>({sources:[]}));state.question.value='安装';await state.ask();expect(state.error.value).toContain('不可用');const fallback=createAiSearch(async()=>({...response,mode:'documents',unresolved:true}));fallback.question.value='安装';await fallback.ask();expect(fallback.result.value?.unresolved).toBe(true)});
});
