import {describe,it,expect} from 'vitest';
import {cartIds,cartTotals,emptyProduct,productPayload,externalPurchaseUrl,canPurchase,type PublicProduct} from './catalog-client';
import {createCatalogCart,CART_KEY} from './catalog-cart';
const item=(extra:Partial<PublicProduct>={}):PublicProduct=>({id:'p1',name:'设备',slug:'device',kind:'DEVICE',price:'0.10',currency:'CNY',stock:1,sales:0,description:'',descriptionHtml:'',summary:null,compareAtPrice:null,coverUrl:null,gallery:[],categoryId:null,available:true,externalUrl:'https://example.invalid/pay',...extra});
describe('stage 9 independent cart',()=>{
  it('imports only IDs from legacy data and bounds corrupted/forged storage',()=>{expect(cartIds('[{"id":"p1","externalUrl":"javascript:evil()","price":0}]')).toEqual(['p1']);expect(cartIds('{bad')).toEqual([]);expect(cartIds({version:1,ids:['p1','p1','../a',null]})).toEqual(['p1']);expect(cartIds(Array.from({length:150},(_,i)=>'p'+i))).toHaveLength(100)});
  it('shares reactive items, prevents duplicates and persists only IDs',async()=>{const values=new Map<string,string>(),cart=createCatalogCart(async()=>({items:[item()],unavailableIds:[]}),{getItem:key=>values.get(key)||null,setItem:(key,value)=>{values.set(key,value)}});expect(cart.add(item())).toBe('');await cart.refresh();expect(cart.items.value[0].name).toBe('设备');expect(cart.add(item())).toContain('已在');expect(JSON.parse(values.get(CART_KEY)!)).toEqual({version:1,ids:['p1']});expect(values.get(CART_KEY)).not.toContain('externalUrl');cart.remove('p1');expect(cart.ids.value).toEqual([])});
  it('refuses sold-out items and fails closed when resolving latest data fails',async()=>{const cart=createCatalogCart(async()=>{throw new Error('offline')});expect(cart.add(item({stock:0}))).toContain('售罄');cart.add(item());await cart.refresh();expect(cart.error.value).toContain('购买链接已暂停');expect(cart.items.value).toEqual([])});
  it('excludes removed IDs and discards stale in-flight responses',async()=>{let complete!:(value:any)=>void;const cart=createCatalogCart(()=>new Promise(resolve=>{complete=resolve}));cart.add(item());cart.clear();complete({items:[item()],unavailableIds:[]});await Promise.resolve();expect(cart.ids.value).toEqual([]);expect(cart.items.value).toEqual([]);expect(cart.loading.value).toBe(false)});
  it('refreshes changed prices, sold-out status and missing products',async()=>{let result={items:[item()],unavailableIds:[] as string[]};const cart=createCatalogCart(async()=>result);cart.add(item());await cart.refresh();result={items:[item({price:'20.00',stock:0,available:false})],unavailableIds:[]};await cart.refresh();expect(canPurchase(cart.items.value[0])).toBe(false);expect(cart.totals.value).toEqual([]);result={items:[],unavailableIds:['p1']};await cart.refresh();expect(cart.missing.value).toEqual(['p1'])});
  it('synchronizes storage events and preserves in-memory operation without storage permission',async()=>{const cart=createCatalogCart(async(ids)=>({items:ids.map(id=>item({id})),unavailableIds:[]}),{getItem:()=>{throw new Error()},setItem:()=>{throw new Error()}});cart.read();cart.add(item());await cart.refresh();expect(cart.storageWarning.value).toBeTruthy();expect(cart.items.value).toHaveLength(1);cart.sync(JSON.stringify({version:1,ids:['p2']}));await cart.refresh();expect(cart.items.value[0].id).toBe('p2');cart.sync(null);expect(cart.ids.value).toEqual([])});
  it('totals exact cents per currency, never converts or sums unavailable products',()=>{expect(cartTotals([item(),item({id:'p2',price:'0.20'}),item({id:'p3',currency:'USD',price:'2.00'}),item({id:'p4',available:false,price:'99.00'})])).toEqual([{currency:'CNY',amount:'0.30'},{currency:'USD',amount:'2.00'}])});
  it('rejects unsafe links and never submits system/identity fields with product drafts',()=>{for(const value of ['javascript:x','//example.com','/checkout','https://a:b@example.com'])expect(externalPurchaseUrl(value)).toBe('');const payload=productPayload({...emptyProduct(),id:'p',revision:2,status:'PUBLISHED',publishedSnapshot:{},orderId:'x'});expect(payload.baseRevision).toBe(2);expect(payload.status).toBeUndefined();expect(payload.orderId).toBeUndefined();expect(payload.publishedSnapshot).toBeUndefined()});
});
