import { afterEach, describe, expect, it, vi } from 'vitest';
import { createPluginRuntime, type Snippet } from './plugin-runtime';
const snippet:Snippet={id:'one',revision:1,position:'HEAD',delayMs:3000,code:'<script>fixture</script>'};
afterEach(()=>vi.useRealTimers());
describe('stage11 plugin lifecycle',()=>{
  it('enforces 3000ms client minimum and executes once across refreshes/routes',()=>{vi.useFakeTimers();const run=vi.fn(),runtime=createPluginRuntime({run,reload:vi.fn(),isPublic:()=>true});runtime.sync([{...snippet,delayMs:1}]);vi.advanceTimersByTime(2999);expect(run).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(run).toHaveBeenCalledTimes(1);runtime.sync([{...snippet,delayMs:1}]);vi.advanceTimersByTime(10000);expect(run).toHaveBeenCalledTimes(1);runtime.stop()});
  it('cancels pending disabled code and stale revisions before execution',()=>{vi.useFakeTimers();const run=vi.fn(),runtime=createPluginRuntime({run,reload:vi.fn(),isPublic:()=>true});runtime.sync([snippet]);vi.advanceTimersByTime(2000);runtime.sync([]);vi.advanceTimersByTime(2000);expect(run).not.toHaveBeenCalled();runtime.sync([snippet]);vi.advanceTimersByTime(2000);runtime.sync([{...snippet,revision:2}]);vi.advanceTimersByTime(1000);expect(run).not.toHaveBeenCalled();vi.advanceTimersByTime(2000);expect(run.mock.calls[0][0].revision).toBe(2);runtime.stop()});
  it('never executes in admin or after unmount',()=>{vi.useFakeTimers();let isPublic=true;const run=vi.fn(),runtime=createPluginRuntime({run,reload:vi.fn(),isPublic:()=>isPublic});runtime.sync([snippet]);isPublic=false;vi.advanceTimersByTime(3000);expect(run).not.toHaveBeenCalled();isPublic=true;runtime.sync([snippet]);runtime.stop();vi.advanceTimersByTime(3000);expect(run).not.toHaveBeenCalled()});
  it('reloads exactly once when executed code is disabled or replaced',()=>{vi.useFakeTimers();const reload=vi.fn(),runtime=createPluginRuntime({run:vi.fn(),reload,isPublic:()=>true});runtime.sync([snippet]);vi.advanceTimersByTime(3000);expect(runtime.hasExecuted()).toBe(true);runtime.sync([]);runtime.sync([]);expect(reload).toHaveBeenCalledTimes(1);runtime.stop()});
  it('rejects malformed position and isolates one throwing plugin from the next',()=>{vi.useFakeTimers();const run=vi.fn(()=>{throw Error('failure')}),warn=vi.spyOn(console,'warn').mockImplementation(()=>{});const runtime=createPluginRuntime({run,reload:vi.fn(),isPublic:()=>true});runtime.sync([{...snippet,position:'bad' as any}, {...snippet,id:'valid'},{...snippet,id:'next'}]);vi.advanceTimersByTime(3000);expect(run).toHaveBeenCalledTimes(2);expect(warn).toHaveBeenCalledTimes(2);warn.mockRestore();runtime.stop()});
});
