<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import {api,currentAdminAccount} from '../api';
import {mediaError} from '../media-client';
const role=currentAdminAccount()?.role,canEdit=!!role&&role!=='VIEWER',canBatch=role==='ADMIN'||role==='SUPER_ADMIN',canConfigure=role==='SUPER_ADMIN';
const status=ref<any>(),form=ref<any>(),saved=ref(''),documents=ref<any[]>([]),jobs=ref<any[]>([]),docPage=ref(1),jobPage=ref(1),docTotal=ref(0),jobTotal=ref(0),filter=ref(''),error=ref(''),loading=ref(false),busy=ref(false),nextCursor=ref<string|null>(null),batchStarted=ref(false);
const dirty=computed(()=>!!form.value&&JSON.stringify(form.value)!==saved.value);
defineExpose({hasUnsavedChanges:()=>dirty.value,isBusy:()=>busy.value});
let generation=0,alive=true,timer:ReturnType<typeof setInterval>|undefined;
function assignSettings(row:any){form.value={baseRevision:row.revision,enabled:row.enabled,autoIndexEnabled:row.autoIndexEnabled,globalAssistantEnabled:row.globalAssistantEnabled,topK:row.topK,minimumScore:row.minimumScore,perMinute:row.perMinute,globalPerMinute:row.globalPerMinute};saved.value=JSON.stringify(form.value)}
async function load(quiet=false){if(quiet&&(loading.value||busy.value))return;const request=++generation;loading.value=true;try{const [s,d,j]=await Promise.all([api.get('/admin/rag/status'),api.get('/admin/rag/documents',{params:{page:docPage.value,limit:20}}),api.get('/admin/rag/jobs',{params:{page:jobPage.value,limit:20,status:filter.value||undefined}})]);if(!alive||request!==generation)return;status.value=s.data;if(!dirty.value)assignSettings(s.data.settings);documents.value=d.data.items;docTotal.value=d.data.total;jobs.value=j.data.items;jobTotal.value=j.data.total;error.value=''}catch(e){if(alive&&request===generation)error.value=mediaError(e)}finally{if(request===generation)loading.value=false}}
async function action(work:()=>Promise<unknown>,message:string){if(busy.value)return;busy.value=true;try{await work();ElMessage.success(message);await load()}catch(e){ElMessage.error(mediaError(e))}finally{busy.value=false}}
async function save(){if(!canConfigure||!dirty.value)return;await action(async()=>{const {data}=await api.patch('/admin/rag/settings',form.value);assignSettings(data)},'AI 配置已保存')}
async function reset(){if(!status.value)return;try{if(dirty.value)await ElMessageBox.confirm('放弃未保存的 AI 配置，读取最新值？','确认重载');assignSettings(status.value.settings);await load()}catch{}}
async function feed(doc:any){if(!canEdit)return;try{await ElMessageBox.confirm(doc.ragEnabled?'关闭后立即排除该内容，并取消未完成索引任务。':'仅已发布快照会加入知识库；草稿不会公开。','确认投喂变更')}catch{return}await action(()=>api.post(`/admin/rag/documents/${doc.id}/feed`,{baseRevision:doc.revision,enabled:!doc.ragEnabled}),'文档投喂状态已更新')}
async function retry(job:any){await action(()=>api.post(`/admin/rag/jobs/${job.id}/retry`,{}),'重试任务已入队')}
async function batch(restart=false){if(!canBatch)return;try{await ElMessageBox.confirm('本次最多将 100 篇已发布且允许投喂的文档入队。模型启用后处理会消耗调用额度，是否继续？','批量索引')}catch{return}await action(async()=>{const {data}=await api.post('/admin/rag/reindex',restart||!nextCursor.value?{}:{afterId:nextCursor.value});nextCursor.value=data.nextCursor;batchStarted.value=true;ElMessage.info(`本批入队 ${data.queued} 篇，跳过 ${data.skipped} 篇`)},'批次已提交，请查看任务状态')}
function beforeUnload(event:BeforeUnloadEvent){if(dirty.value){event.preventDefault();event.returnValue=''}}
onMounted(()=>{load();timer=setInterval(()=>load(true),10000);window.addEventListener('beforeunload',beforeUnload)});onUnmounted(()=>{alive=false;generation++;clearInterval(timer);window.removeEventListener('beforeunload',beforeUnload)});
</script>
<template><section class="rag-manager"><header class="cms-heading"><div><h1>文档投喂 / AI 客服</h1><p>只读取 APPGOG 公开快照，与 Xboard 完全隔离。每 10 秒刷新任务状态，不覆盖未保存配置。</p></div><button :disabled="loading||busy" @click="load()">刷新状态</button></header>
<p v-if="error" role="alert">{{error}} <button @click="load()">重试加载</button></p><p v-if="loading&&!status" role="status">正在加载 AI 运维状态…</p>
<template v-if="status"><div class="rag-counters"><p>外部模型：<b>{{status.provider.configured?'已启用并配置（连接仍需验证）':'未启用或未配置：仅关键词文档检索'}}</b></p><p>后台处理器：{{status.workerEnabled?'已允许运行':'已暂停'}} · 待处理 {{status.jobs.pending}} / 运行中 {{status.jobs.running}} / 失败 {{status.jobs.failed}}</p><p>可投喂文档 {{status.eligibleDocuments}} · 分块 {{status.chunks}} · 今日模型调用 {{status.usage.modelCallsToday}} / {{status.usage.dailyModelCallLimit}}<small>调用次数上限不是金额预算；失败请求也计数，UTC 次日重置。密钥仅从服务端环境读取。</small></p><p>对话模型 {{status.provider.chatModel}} · 向量模型 {{status.provider.embeddingModel}} · {{status.provider.dimensions}} 维</p></div>
<form v-if="form" class="rag-settings" @submit.prevent="save"><h2>AI 服务设置</h2><p v-if="!canConfigure">只读：仅超级管理员可以修改服务设置。</p><fieldset :disabled="!canConfigure||busy"><label><input v-model="form.enabled" type="checkbox">允许公开 AI 问答</label><label><input v-model="form.autoIndexEnabled" type="checkbox">自动为已发布且允许投喂的文档入队</label><small>关闭自动入队不取消已有任务，也不禁止手动入队。需要暂停处理器时设置服务端 AI_WORKER_ENABLED=false 并重启。</small><label><input v-model="form.globalAssistantEnabled" type="checkbox">全站右下角 AI 客服</label><label>返回资料数（1–10）<input v-model.number="form.topK" type="number" min="1" max="10" required></label><label>最低语义相似度（0–1）<input v-model.number="form.minimumScore" type="number" min="0" max="1" step="0.01" required></label><label>单访客每分钟上限（1–60）<input v-model.number="form.perMinute" type="number" min="1" max="60" required></label><label>全站每分钟上限（1–600）<input v-model.number="form.globalPerMinute" type="number" min="1" max="600" required></label></fieldset><p role="status">{{dirty?'AI 配置有未保存的修改':'AI 配置已同步'}} · 版本 {{form.baseRevision}}</p><button v-if="canConfigure" :disabled="busy||!dirty">保存 AI 配置</button> <button type="button" :disabled="busy" @click="reset">重载配置</button></form>
<section aria-label="投喂文档"><h2>CMS 投喂文档</h2><p>草稿标题仅在后台显示；索引和引用始终使用已发布标题及正文。</p><div v-for="doc in documents" :key="doc.id" class="rag-row"><div><strong>{{doc.title}}</strong><small>公开标题：{{doc.publishedTitle||'尚未发布'}} · {{doc.status}} · {{doc.ragEnabled?'允许投喂':'不投喂'}} · 最近索引 {{doc.ragIndexedAt||'尚未完成'}}</small></div><button v-if="canEdit" :disabled="busy" :aria-label="`${doc.ragEnabled?'关闭':'允许'}投喂 ${doc.title}`" @click="feed(doc)">{{doc.ragEnabled?'关闭投喂':'允许投喂'}}</button></div><p v-if="!documents.length">暂无文档，请先在文档 CMS 库创建内容。</p><nav aria-label="投喂文档分页"><button :disabled="loading||docPage<=1" @click="docPage--;load()">上一页文档</button> {{docPage}} / {{Math.max(1,Math.ceil(docTotal/20))}} <button :disabled="loading||docPage*20>=docTotal" @click="docPage++;load()">下一页文档</button></nav></section>
<section aria-label="索引任务"><h2>索引任务与失败恢复</h2><p>发布操作只负责持久入队；后台分块、向量化并提交。失败最多自动尝试 3 次，旧任务不会覆盖新发布版本。</p><div class="ai-actions"><button v-if="canBatch" :disabled="busy" @click="batch(true)">从头提交一批（最多 100 篇）</button><button v-if="canBatch&&nextCursor" :disabled="busy" @click="batch()">继续下一批</button><span v-if="batchStarted&&!nextCursor">当前批次已到末尾</span><label>任务状态<select v-model="filter" @change="jobPage=1;load()"><option value="">全部任务</option><option>PENDING</option><option>RUNNING</option><option>SUCCEEDED</option><option>FAILED</option></select></label></div>
<article v-for="job in jobs" :key="job.id" class="rag-row"><div><strong>{{job.status}} · 尝试 {{job.attemptCount}} / 3</strong><small>文档 {{job.contentId}} · 任务 {{job.id}}</small><small>创建 {{job.createdAt}} · 开始 {{job.startedAt||'未开始'}} · 完成 {{job.finishedAt||'未完成'}}</small><p v-if="job.errorMessage">{{job.errorMessage}}</p></div><button v-if="canEdit&&job.status==='FAILED'" :disabled="busy" @click="retry(job)">重试失败任务</button></article><p v-if="!jobs.length">暂无符合条件的任务</p><nav aria-label="索引任务分页"><button :disabled="loading||jobPage<=1" @click="jobPage--;load()">上一页任务</button> {{jobPage}} / {{Math.max(1,Math.ceil(jobTotal/20))}} <button :disabled="loading||jobPage*20>=jobTotal" @click="jobPage++;load()">下一页任务</button></nav></section></template></section></template>
