<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { api } from '../api';
const props=defineProps<{kind:string}>(); const items=ref<any[]>([]), dialog=ref(false), form=reactive<any>({});
const configs:any={
globalSetting:{resource:'globalSetting',title:'系统设置 / Xboard 配置',key:'key',fields:[['key','配置键','text'],['value','配置 JSON','json'],['public','允许前台读取','boolean']]},
outboundLink:{resource:'outboundLink',title:'普通外跳链接',fields:[['kind','入口类型','select',['LOGIN','REGISTER','PURCHASE','DASHBOARD','TICKET','AFFILIATE']],['label','名称','text'],['destinationUrl','无身份参数的 HTTP/HTTPS URL','text'],['openInNewWindow','新窗口打开','boolean'],['enabled','启用','boolean']]}};
const cfg=computed(()=>configs[props.kind]||configs.globalSetting), visible=computed(()=>cfg.value.filter?items.value.filter(cfg.value.filter):items.value);
async function load(){items.value=(await api.get(`/admin/${cfg.value.resource}`)).data}
function defaults(){const o:any={...cfg.value.defaults};for(const [k,,t,opts] of cfg.value.fields)if(o[k]===undefined)o[k]=t==='boolean'?false:t==='number'?0:t==='select'?opts[0]:t==='json'?'{}':'';return o}
function edit(x?:any){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,x||defaults(),{__existing:!!x,__originalKey:x?.key});for(const f of cfg.value.fields)if(f[2]==='json'&&typeof form[f[0]]!=='string')form[f[0]]=JSON.stringify(form[f[0]]||{},null,2);dialog.value=true}
async function save(){const data:any={...form};for(const f of cfg.value.fields){if(f[2]==='json')try{data[f[0]]=JSON.parse(data[f[0]]||'{}')}catch{return ElMessage.error(`${f[1]} 不是合法 JSON`)}if(f[2]==='number')data[f[0]]=data[f[0]]===''?null:Number(data[f[0]]);if(f[2]==='datetime')data[f[0]]=data[f[0]]?new Date(data[f[0]]).toISOString():null}const existing=!!form.__existing,id=form.id||form.__originalKey;delete data.id;delete data.createdAt;delete data.updatedAt;delete data.__existing;delete data.__originalKey;if(existing)await api.patch(`/admin/${cfg.value.resource}/${id}`,data);else await api.post(`/admin/${cfg.value.resource}`,data);dialog.value=false;await load();ElMessage.success('已保存')}
async function remove(x:any){await ElMessageBox.confirm('确定删除？此操作无法撤销。','删除确认',{type:'warning'});await api.delete(`/admin/${cfg.value.resource}/${x.id||x.key}`);await load()}
watch(()=>props.kind,load);onMounted(load);
</script>
<template><div class="resource"><div class="resource-head"><div><h1>{{cfg.title}}</h1><p>独立数据源管理；发布后的内容可绑定至页面组件。</p></div><el-button type="primary" @click="edit()">＋ 新建</el-button></div><el-table :data="visible" stripe><el-table-column v-for="f in cfg.fields.slice(0,5)" :prop="f[0]" :label="f[1]" show-overflow-tooltip/><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
<el-dialog v-model="dialog" :title="form.id?'编辑':'新建'" width="680"><el-form label-position="top"><el-form-item v-for="f in cfg.fields" :label="f[1]"><el-switch v-if="f[2]==='boolean'" v-model="form[f[0]]"/><el-select v-else-if="f[2]==='select'" v-model="form[f[0]]"><el-option v-for="x in f[3]" :label="x" :value="x"/></el-select><el-input v-else-if="f[2]==='textarea'||f[2]==='json'" v-model="form[f[0]]" type="textarea" :rows="f[2]==='json'?7:5"/><el-date-picker v-else-if="f[2]==='datetime'" v-model="form[f[0]]" type="datetime"/><el-input v-else v-model="form[f[0]]" :type="f[2]"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
