import {AiGatewayService,KNOWLEDGE_SYSTEM_PROMPT} from './ai-gateway.service';
import {providerFetch} from './ai-provider-http';
import {cmsDatabaseFixture} from './cms-test-fixture';
jest.mock('./ai-provider-http',()=>({...jest.requireActual('./ai-provider-http'),providerFetch:jest.fn()}));
describe('installed OpenAI SDK request contract (mock HTTP; no paid model)',()=>{
  const db=cmsDatabaseFixture(),gateway=new AiGatewayService(db),names=['AI_EXTERNAL_ENABLED','OPENAI_API_KEY','OPENAI_BASE_URL','AI_DAILY_MODEL_CALL_LIMIT'];let saved:any={};let bodies:any[],reply:any;
  beforeAll(()=>{for(const name of names)saved[name]=process.env[name]});afterAll(()=>{for(const name of names)if(saved[name]===undefined)delete process.env[name];else process.env[name]=saved[name]});
  beforeEach(()=>{db.reset();process.env.AI_EXTERNAL_ENABLED='true';process.env.OPENAI_API_KEY='sk-test-never-real';process.env.OPENAI_BASE_URL='https://api.example.com/v1';process.env.AI_DAILY_MODEL_CALL_LIMIT='200';bodies=[];reply={data:[{index:0,embedding:Array(1536).fill(0.1)}]};(providerFetch as jest.Mock).mockImplementation(()=>async(_url:any,init:any)=>{bodies.push(JSON.parse(init.body));return new Response(JSON.stringify(reply),{status:200,headers:{'content-type':'application/json'}})})});
  it('requests bounded float vectors in the schema dimension and redacts credentials',async()=>{expect((await gateway.embed(['公开资料']))[0]).toHaveLength(1536);expect(bodies[0]).toMatchObject({input:['公开资料'],dimensions:1536,encoding_format:'float'});expect(JSON.stringify(gateway.status())).not.toContain('sk-test');expect(db.rows('aiRateBucket')[0].count).toBe(1)});
  it.each(['wrong-dimensions','zero-vector','wrong-index','missing-row'])('rejects invalid embedding %s',async(failure)=>{if(failure==='wrong-dimensions')reply.data[0].embedding=[1];if(failure==='zero-vector')reply.data[0].embedding=Array(1536).fill(0);if(failure==='wrong-index')reply.data[0].index=2;if(failure==='missing-row')reply.data=[];await expect(gateway.embed(['公开资料'])).rejects.toThrow('INVALID_EMBEDDING_VECTOR')});
  it('requests only grounded JSON with no tools, no storage and bounded output',async()=>{reply={choices:[{finish_reason:'stop',message:{content:'{"answer":"说明","sourceIds":["a"],"unresolved":false}'}}]};await gateway.answer('如何安装',[{id:'a',title:'教程',text:'公开资料'}]);expect(bodies[0]).toMatchObject({store:false,max_completion_tokens:1500,response_format:{type:'json_object'}});expect(bodies[0].tools).toBeUndefined();expect(bodies[0].messages[0]).toEqual({role:'system',content:KNOWLEDGE_SYSTEM_PROMPT});expect(bodies[0].messages[1].content).toContain('untrustedKnowledge');reply.choices[0].finish_reason='length';await expect(gateway.answer('安装',[{id:'a',title:'教程',text:'公开资料'}])).rejects.toThrow('INCOMPLETE')});
  it('rejects requests before model HTTP when disabled, malformed or over daily budget',async()=>{process.env.AI_EXTERNAL_ENABLED='false';await expect(gateway.embed(['说明'])).rejects.toThrow('NOT_CONFIGURED');expect(bodies).toHaveLength(0);expect(db.rows('aiRateBucket')).toHaveLength(0);expect(gateway.profile()).toBe('text-only-v1');process.env.AI_EXTERNAL_ENABLED='true';await expect(gateway.embed(['x'.repeat(2501)])).rejects.toThrow('INPUT');process.env.AI_DAILY_MODEL_CALL_LIMIT='1';await gateway.embed(['说明']);await expect(gateway.embed(['说明'])).rejects.toMatchObject({status:429});expect(bodies).toHaveLength(1)});
});
