import {EventEmitter} from 'node:events';
import {lookup} from 'node:dns/promises';
import {request} from 'node:https';
import {providerBaseUrl,providerFetch,publicProviderAddress} from './ai-provider-http';
jest.mock('node:dns/promises',()=>({lookup:jest.fn()}));
jest.mock('node:https',()=>({request:jest.fn()}));
describe('server model HTTP egress boundary (no real network)',()=>{
  beforeEach(()=>{jest.clearAllMocks();(lookup as jest.Mock).mockResolvedValue([{address:'8.8.8.8',family:4}])});
  it.each(['http://api.example.com/v1','https://localhost/v1','https://127.0.0.1/v1','https://[::1]/v1','https://169.254.169.254/v1','https://u:p@api.example.com/v1','https://api.example.com/v1?token=x','https://api.example.com:8080/v1','https://service.internal/v1'])('rejects invalid/private base %s',url=>expect(()=>providerBaseUrl(url)).toThrow());
  it('accepts only public unicast addresses',()=>{for(const address of ['10.0.0.1','172.16.1.1','192.168.0.1','100.64.0.1','224.0.0.1','198.18.0.1','::ffff:127.0.0.1','fc00::1','2001:db8::1'])expect(publicProviderAddress(address)).toBe(false);expect(publicProviderAddress('8.8.8.8')).toBe(true);expect(publicProviderAddress('2606:4700:4700::1111')).toBe(true);expect(providerBaseUrl('https://api.openai.com/v1/')).toBe('https://api.openai.com/v1')});
  it('rejects foreign endpoint/method and mixed public/private DNS before opening a socket',async()=>{const fetcher=providerFetch('https://api.example.com/v1');await expect(fetcher('https://evil.example.com/v1/embeddings',{method:'POST',body:'{}'})).rejects.toThrow();await expect(fetcher('https://api.example.com/v1/files',{method:'POST',body:'{}'})).rejects.toThrow();(lookup as jest.Mock).mockResolvedValue([{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}]);await expect(fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'{}'})).rejects.toThrow('PRIVATE');expect(request).not.toHaveBeenCalled()});
  function network(status:number,body:Buffer){const req:any=new EventEmitter();req.setTimeout=jest.fn();req.destroy=(error:Error)=>{req.emit('error',error)};req.end=()=>{};(request as jest.Mock).mockImplementation((_url,options,callback)=>{req.end=()=>queueMicrotask(()=>{const res:any=new EventEmitter();res.statusCode=status;res.headers={'content-type':'application/json'};res.resume=jest.fn();callback(res);if(status<300){res.emit('data',body);res.emit('end')}});return req});return req}
  it('pins validated DNS and caps outbound/inbound bytes',async()=>{const fetcher=providerFetch('https://api.example.com/v1');network(200,Buffer.from('{"ok":true}'));expect(await (await fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'{}'})).json()).toEqual({ok:true});const options=(request as jest.Mock).mock.calls[0][1],callback=jest.fn();options.lookup('ignored',{all:false},callback);expect(callback).toHaveBeenCalledWith(null,'8.8.8.8',4);network(200,Buffer.alloc(2*1024*1024+1));await expect(fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'{}'})).rejects.toThrow('TOO_LARGE');await expect(fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'x'.repeat(512*1024+1)})).rejects.toThrow('BODY')});
  it('does not follow redirects and honors an already-aborted request',async()=>{network(302,Buffer.alloc(0));const fetcher=providerFetch('https://api.example.com/v1');await expect(fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'{}'})).rejects.toThrow('REDIRECT');const controller=new AbortController();controller.abort();await expect(fetcher('https://api.example.com/v1/embeddings',{method:'POST',body:'{}',signal:controller.signal})).rejects.toThrow('ABORTED')});
  it('bounds stalled DNS resolution without opening a connection',async()=>{jest.useFakeTimers();try{(lookup as jest.Mock).mockImplementation(()=>new Promise(()=>{}));const pending=expect(providerFetch('https://api.example.com/v1')('https://api.example.com/v1/embeddings',{method:'POST',body:'{}'})).rejects.toThrow('DNS_TIMEOUT');await jest.advanceTimersByTimeAsync(5000);await pending;expect(request).not.toHaveBeenCalled()}finally{jest.useRealTimers()}});
});
