import {AiPolicyService,AI_DEFAULTS} from './ai-policy.service';
import {aiClientAddress} from './ai.service';
import {cmsDatabaseFixture} from './cms-test-fixture';
describe('persistent AI request and model budgets (fixture, not DB isolation proof)',()=>{
  const db=cmsDatabaseFixture(),policy=new AiPolicyService(db),actor:any={id:'SUPER_ADMIN'};let limit:string|undefined,proxy:string|undefined;
  beforeAll(()=>{limit=process.env.AI_DAILY_MODEL_CALL_LIMIT;proxy=process.env.AI_TRUSTED_PROXY_IPS});afterAll(()=>{for(const [name,value] of [['AI_DAILY_MODEL_CALL_LIMIT',limit],['AI_TRUSTED_PROXY_IPS',proxy]])if(value===undefined)delete process.env[name!];else process.env[name!]=value});beforeEach(()=>db.reset());
  const settings=(extra:any={})=>{const {id,revision,...rest}=AI_DEFAULTS;return {...rest,baseRevision:0,...extra}};
  it('atomically saves versions and redacts public config',async()=>{await policy.save(settings({globalAssistantEnabled:true}),actor);await expect(policy.save(settings(),actor)).rejects.toMatchObject({status:409});expect(await policy.publicConfig()).toEqual({enabled:true,globalAssistantEnabled:true,maxQuestionLength:2000,ticketUrl:''});expect(db.rows('auditLog')).toHaveLength(1);db.failAudit=true;await expect(policy.save(settings({baseRevision:1,enabled:false}),actor)).rejects.toThrow();expect((await policy.settings()).enabled).toBe(true)});
  it('shares quotas across service instances, rolls back rejected counts and stores no raw visitor address',async()=>{await policy.save(settings({perMinute:1,globalPerMinute:2}),actor);await policy.requestQuota('8.8.8.8');await expect(new AiPolicyService(db).requestQuota('8.8.8.8')).rejects.toMatchObject({status:429});await policy.requestQuota('1.1.1.1');await expect(policy.requestQuota('9.9.9.9')).rejects.toMatchObject({status:429});expect(db.rows('aiRateBucket').find((row:any)=>row.key.endsWith(':global')).count).toBe(2);expect(JSON.stringify(db.rows('aiRateBucket'))).not.toMatch(/8\.8\.8\.8|1\.1\.1\.1/)});
  it('limits model attempts and resets by UTC day',async()=>{process.env.AI_DAILY_MODEL_CALL_LIMIT='1';await policy.modelQuota();await expect(policy.modelQuota()).rejects.toMatchObject({status:429});expect((await policy.usage()).modelCallsToday).toBe(1);const now=Date.now();const clock=jest.spyOn(Date,'now').mockReturnValue(now+86400000);try{await policy.modelQuota();expect((await policy.usage()).modelCallsToday).toBe(1)}finally{clock.mockRestore()}});
  it('retries serialization conflicts within a bound',async()=>{const transaction=db.$transaction;let calls=0;db.$transaction=async(action:any)=>{calls++;if(calls<3)throw {code:'P2034'};return transaction(action)};try{await policy.modelQuota();expect(calls).toBe(3)}finally{db.$transaction=transaction}});
  it('ignores spoofed forwarding unless immediate proxy is explicitly trusted',()=>{const req:any={socket:{remoteAddress:'::ffff:127.0.0.1'},headers:{'x-forwarded-for':'8.8.8.8, 1.1.1.1'}};process.env.AI_TRUSTED_PROXY_IPS='';expect(aiClientAddress(req)).toBe('127.0.0.1');process.env.AI_TRUSTED_PROXY_IPS='127.0.0.1';expect(aiClientAddress(req)).toBe('1.1.1.1');req.headers['x-forwarded-for']='invalid';expect(aiClientAddress(req)).toBe('127.0.0.1')});
});
