import {AiService} from './ai.service';
import {AI_DEFAULTS} from './ai-policy.service';
describe('AI in-flight limits and live disable checks',()=>{
  const document={id:'doc',title:'公开教程',slug:'help/install',text:'公开安装说明',hash:'hash',score:1};
  function setup(){let enabled=true;const policy:any={requestQuota:async()=>({...AI_DEFAULTS,enabled}),publicConfig:async()=>({ticketUrl:''}),settings:async()=>({enabled})},knowledge:any={search:jest.fn(async()=>({documents:[document],mode:'keyword'})),stillPublic:jest.fn(async(docs:any)=>docs)},gateway:any={status:()=>({configured:true}),answer:jest.fn(async()=>JSON.stringify({answer:'安装说明',sourceIds:['doc'],unresolved:false}))};return {service:new AiService(knowledge,gateway,policy),knowledge,gateway,disable:()=>enabled=false}}
  it('rejects normalized expansion beyond 2000 characters before retrieval',async()=>{const {service,knowledge}=setup();await expect(service.search('㍿'.repeat(501),'visitor')).rejects.toMatchObject({status:400});expect(knowledge.search).not.toHaveBeenCalled()});
  it('bounds active requests and releases slots after completion',async()=>{const {service,knowledge}=setup();const releases:((value:any)=>void)[]=[];knowledge.search.mockImplementation(()=>new Promise(resolve=>releases.push(resolve)));const pending=[];for(let n=0;n<8;n++){pending.push(service.search('安装','visitor'));await Promise.resolve();await Promise.resolve()}await expect(service.search('安装','visitor')).rejects.toMatchObject({status:429});for(const release of releases)release({documents:[document],mode:'keyword'});expect((await Promise.all(pending)).every(row=>row.mode==='answer')).toBe(true);knowledge.search.mockResolvedValue({documents:[],mode:'keyword'});expect((await service.search('安装','visitor')).mode).toBe('documents')});
  it('does not return generated answers after service is disabled during model work',async()=>{const {service,gateway,disable}=setup();gateway.answer.mockImplementation(async()=>{disable();return JSON.stringify({answer:'安装说明',sourceIds:['doc'],unresolved:false})});expect(await service.search('安装','visitor')).toMatchObject({mode:'disabled',sources:[]})});
});
