import 'reflect-metadata';
import {ValidationPipe} from '@nestjs/common';import type {NestExpressApplication} from '@nestjs/platform-express';import {JwtModule,JwtService} from '@nestjs/jwt';import {Test} from '@nestjs/testing';import {randomUUID} from 'node:crypto';
import {ADMIN_ROLES,type AdminRoleName} from './auth.types';import {JWT_AUDIENCE,JWT_ISSUER} from './security.config';import {CatalogController,PublicCatalogController} from './catalog.controller';import {CatalogService} from './catalog.service';import {CategoryController} from './cms.controller';import {CmsService} from './cms.service';import {KnowledgeService} from './knowledge.service';import {PrismaService} from './prisma.service';import {AdminController} from './admin.controller';import {cmsDatabaseFixture} from './cms-test-fixture';
describe('stage 9 real HTTP catalog contract (in-memory database only)',()=>{
  const db=cmsDatabaseFixture(),tokens:Partial<Record<AdminRoleName,string>>={};let app:NestExpressApplication,base:string;
  beforeAll(async()=>{const module=await Test.createTestingModule({imports:[JwtModule.register({secret:randomUUID(),signOptions:{issuer:JWT_ISSUER,audience:JWT_AUDIENCE,expiresIn:'15m'}})],controllers:[CatalogController,PublicCatalogController,CategoryController,AdminController],providers:[CatalogService,CmsService,KnowledgeService,{provide:PrismaService,useValue:db}]}).compile();app=module.createNestApplication<NestExpressApplication>({logger:false});app.setGlobalPrefix('api/v1');app.useBodyParser('json',{limit:'512kb'});app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.listen(0,'127.0.0.1');base=`${await app.getUrl()}/api/v1`;for(const role of ADMIN_ROLES)tokens[role]=await module.get(JwtService).signAsync({sub:role,sid:role,role,type:'access'})});
  beforeEach(()=>db.reset());afterAll(async()=>app?.close());
  const data=(extra:any={})=>({name:'测试设备',slug:'device',kind:'DEVICE',price:'19.90',stock:4,sales:8,currency:'CNY',description:'设备详细说明',externalUrl:'https://supplier.example.invalid/pay?item=device',...extra});
  function request(path:string,role?:AdminRoleName,method='GET',body?:any){return fetch(base+path,{method,headers:{...(role?{Authorization:`Bearer ${tokens[role]}`}:{ }),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})})}
  async function ok(path:string,role?:AdminRoleName,method='GET',body?:any){const result=await request(path,role,method,body),bodyResult=await result.json();expect({status:result.status,error:result.ok?null:bodyResult}).toEqual({status:method==='POST'?201:200,error:null});return bodyResult}
  const create=(extra:any={})=>ok('/admin/product','EDITOR','POST',data(extra));const publish=(row:any)=>ok(`/admin/product/${row.id}/publish`,'EDITOR','POST',{baseRevision:row.revision});
  it('requires authentication and protects all write operations against viewers',async()=>{expect((await request('/admin/product')).status).toBe(401);await ok('/admin/product','VIEWER');expect((await request('/admin/product','VIEWER','POST',data())).status).toBe(403);const row=await create();for(const method of ['PATCH','DELETE'])expect((await request(`/admin/product/${row.id}`,'VIEWER',method,data({baseRevision:1}))).status).toBe(403);for(const action of ['publish','status'])expect((await request(`/admin/product/${row.id}/${action}`,'VIEWER','POST',{baseRevision:1,status:'OFFLINE'})).status).toBe(403)});
  it('rejects traffic kinds, arbitrary system fields and transaction/identity payloads',async()=>{for(const extra of [{kind:'TRAFFIC'},{xboardPlanId:'x'},{orderId:'x'},{userId:'x'},{status:'PUBLISHED'},{publishedSnapshot:{}},{publishedPrice:'1'},{revision:10}])expect((await request('/admin/product','EDITOR','POST',data(extra))).status).toBe(400);expect(db.rows('product')).toHaveLength(0);for(const path of ['/public/orders','/public/checkout','/public/payment/callback'])expect((await request(path,undefined,'POST',{})).status).toBe(404)});
  it('validates numeric bounds, currency, URLs, album, required values and unknown queries',async()=>{for(const extra of [{name:' '},{stock:-1},{stock:1.5},{sales:-1},{stock:2147483648},{price:'1.001'},{price:-1},{compareAtPrice:'1.00'},{currency:'usd'},{gallery:{}},{gallery:['']},{gallery:Array.from({length:31},(_,i)=>`https://example.com/${i}.png`)},{externalUrl:'javascript:x'},{categoryId:null},{price:null},{gallery:null}])expect((await request('/admin/product','EDITOR','POST',data(extra))).status).toBe(400);for(const query of ['page=0','limit=101','sort=random','unknown=x','currency=US'])expect((await request(`/public/products?${query}`)).status).toBe(400)});
  it('keeps drafts private and publishes complete details, album and exact prices',async()=>{let row=await create({gallery:['https://example.com/a.png','/api/v1/public/media/id'],coverUrl:'https://example.com/cover.png',sku:'DEVICE-1'});expect(await ok('/public/products')).toHaveLength(0);expect((await request(`/public/products/${row.id}`)).status).toBe(404);row=await publish(row);const live=await ok(`/public/products/${row.id}`);expect(live).toMatchObject({name:'测试设备',price:'19.90',stock:4,sales:8,available:true});expect(live.gallery).toHaveLength(2);expect(live.descriptionHtml).toContain('设备详细说明');expect(live.revision).toBeUndefined();expect(live.publishedSnapshot).toBeUndefined()});
  it('isolates draft changes from public price, stock, link, category, details and sorting',async()=>{const cat=await ok('/admin/category','EDITOR','POST',{name:'设备分类',slug:'devices',scope:'PRODUCT'});let row=await publish(await create({categoryId:cat.id}));row=await ok(`/admin/product/${row.id}`,'EDITOR','PATCH',data({name:'未发布名称',price:'1.00',stock:0,sales:100,slug:'changed',externalUrl:'https://example.com/new',baseRevision:row.revision}));const live=await ok(`/public/products/${row.id}`);expect(live).toMatchObject({name:'测试设备',price:'19.90',stock:4,categoryId:cat.id});expect((await ok('/public/product-search?search=未发布名称')).total).toBe(0);expect((await ok(`/public/product-search?categoryId=${cat.id}`)).total).toBe(1);expect((await request(`/admin/category/${cat.id}`,'ADMIN','DELETE',{baseRevision:1})).status).toBe(409);await publish(row);expect((await ok(`/public/products/${row.id}`)).available).toBe(false)});
  it('requires purchase link on publication but permits incomplete drafts',async()=>{const row=await create({externalUrl:''});expect((await request(`/admin/product/${row.id}/publish`,'EDITOR','POST',{baseRevision:1})).status).toBe(400);expect((await ok('/public/products')).length).toBe(0)});
  it('checks stale revisions, unique slug/SKU and missing references',async()=>{const row=await create({sku:'unique'});expect((await request('/admin/product','EDITOR','POST',data())).status).toBe(409);expect((await request('/admin/product','EDITOR','POST',data({slug:'second',sku:'unique'}))).status).toBe(409);expect((await request(`/admin/product/${row.id}`,'EDITOR','PATCH',data())).status).toBe(400);expect((await request(`/admin/product/${row.id}/publish`,'EDITOR','POST',{baseRevision:99})).status).toBe(409);expect((await request('/admin/product/missing','EDITOR','PATCH',data({baseRevision:1}))).status).toBe(404);const category=await ok('/admin/category','EDITOR','POST',{name:'知识分类',slug:'docs'});expect((await request('/admin/product','EDITOR','POST',data({slug:'other',categoryId:category.id}))).status).toBe(400)});
  it('supports product descendants and sales/price/time sorts with pagination',async()=>{const root=await ok('/admin/category','EDITOR','POST',{name:'设备',slug:'root',scope:'PRODUCT'});const child=await ok('/admin/category','EDITOR','POST',{name:'子分类',slug:'child',parentId:root.id,scope:'PRODUCT'});const first=await publish(await create({categoryId:child.id,price:'9.00',sales:1}));const second=await publish(await create({slug:'second',categoryId:root.id,price:'100.00',sales:10}));expect((await ok(`/public/products?categoryId=${root.id}&sort=priceAsc`)).map((x:any)=>x.id)).toEqual([first.id,second.id]);expect((await ok('/public/products?sort=priceDesc'))[0].id).toBe(second.id);expect((await ok('/public/products?sort=salesDesc'))[0].id).toBe(second.id);expect((await ok('/public/products?sort=newest'))[0].id).toBe(second.id);expect((await ok('/public/products?sort=oldest'))[0].id).toBe(first.id);expect((await ok('/public/product-search?page=2&limit=1')).items).toHaveLength(1);expect((await ok('/public/product-search?currency=USD')).total).toBe(0)});
  it('archives/restores with correct roles, retains rows and hides offline cart products',async()=>{let row=await publish(await create());expect((await request(`/admin/product/${row.id}/status`,'EDITOR','POST',{status:'ARCHIVED',baseRevision:row.revision})).status).toBe(403);row=await ok(`/admin/product/${row.id}`,'ADMIN','DELETE',{baseRevision:row.revision});expect(db.rows('product')).toHaveLength(1);expect((await request(`/admin/product/${row.id}/publish`,'ADMIN','POST',{baseRevision:row.revision})).status).toBe(400);expect((await request(`/admin/product/${row.id}/status`,'EDITOR','POST',{baseRevision:row.revision,status:'DRAFT'})).status).toBe(403);row=await ok(`/admin/product/${row.id}/status`,'ADMIN','POST',{baseRevision:row.revision,status:'DRAFT'});row=await publish(row);await ok(`/admin/product/${row.id}/status`,'EDITOR','POST',{baseRevision:row.revision,status:'OFFLINE'});expect((await ok('/public/products/resolve',undefined,'POST',{ids:[row.id]})).unavailableIds).toEqual([row.id])});
  it('resolves IDs only, never trusts injected prices/links or modifies stock/sales',async()=>{const row=await publish(await create()),sold=await publish(await create({slug:'sold',stock:0}));const initial=structuredClone(db.rows('product'));const result=await ok('/public/products/resolve',undefined,'POST',{ids:[row.id,sold.id,'missing']});expect(result.items).toHaveLength(2);expect(result.items.find((x:any)=>x.id===sold.id).available).toBe(false);expect(result.unavailableIds).toEqual(['missing']);for(const body of [{ids:[row.id],price:0},{ids:[row.id],externalUrl:'javascript:x'},{ids:Array(101).fill('x')},{ids:[row.id,row.id]}])expect((await request('/public/products/resolve',undefined,'POST',body)).status).toBe(400);expect(db.rows('product')).toEqual(initial)});
  it('rolls back create/save/publish/status changes when audit fails',async()=>{const row=await create();db.failAudit=true;expect((await request('/admin/product','EDITOR','POST',data({slug:'other'}))).status).toBe(500);expect((await request(`/admin/product/${row.id}`,'EDITOR','PATCH',data({baseRevision:1,name:'not committed'}))).status).toBe(500);expect((await request(`/admin/product/${row.id}/publish`,'EDITOR','POST',{baseRevision:1})).status).toBe(500);expect((await request(`/admin/product/${row.id}/status`,'ADMIN','POST',{baseRevision:1,status:'ARCHIVED'})).status).toBe(500);expect(db.rows('product')).toHaveLength(1);expect(db.rows('product')[0]).toMatchObject({name:'测试设备',revision:1,status:'DRAFT'});expect(db.rows('auditLog')).toHaveLength(1)});
});
