import { cmsSlug,cmsSnapshot,cmsUrl,cleanCmsHtml,renderCmsBody,validateCategoryParent,descendantIds,normalizeCms } from './cms-content';
import { CmsWriteDto } from './cms.dto';
describe('stage 8 content safety and hierarchy',()=>{
  it('renders Markdown without executable raw HTML and keeps code/lists',()=>{const html=renderCmsBody('# 标题\n\n- **加粗**\n\n<script>alert(1)</script>\n\n```js\nconst x=1\n```','MARKDOWN');expect(html).toContain('<h1>标题</h1>');expect(html).toContain('<strong>加粗</strong>');expect(html).not.toContain('<script>');expect(html).toContain('language-js')});
  it('sanitizes rich text scripts, attributes, SVG, unsafe images and links',()=>{const html=cleanCmsHtml('<p onclick="x()">正常<strong>加粗</strong></p><script>evil()</script><img src="data:image/svg+xml,x" onerror="evil()"><svg onload="evil()"></svg><a href="javascript:evil()">链接</a><iframe src="https://example.com"></iframe>');expect(html).toContain('<strong>加粗</strong>');expect(html).not.toMatch(/onclick|onerror|onload|<script|<svg|<iframe|data:|javascript:/)});
  it('retains media library images and safe outbound link attributes',()=>{expect(cleanCmsHtml('<img src="/api/v1/public/media/id" alt="图"><a href="https://example.com">文档</a>')).toContain('rel="noopener noreferrer"');expect(cleanCmsHtml('<img src="/api/v1/public/media/id" alt="图">')).toContain('alt="图"')});
  it('cleans unsafe legacy snapshot media on read but refuses publishing it',()=>{const doc={type:'ARTICLE',format:'MARKDOWN',body:'正文',coverUrl:'javascript:alert(1)'};expect(cmsSnapshot(doc).snapshot.coverUrl).toBeNull();expect(()=>cmsSnapshot(doc,true)).toThrow()});
  it.each(['javascript:alert(1)','data:text/html,x','//example.com/a','https://user:pass@example.com/a','https:\\example.com/a','https://example.com/a b'])('rejects unsafe address %s',url=>expect(()=>cmsUrl(url)).toThrow());
  it('accepts signed m3u8 URLs but rejects other video types',()=>{expect(cmsUrl('https://example.com/a.m3u8?sig=abc',true)).toContain('?sig=abc');expect(()=>cmsUrl('https://example.com/a.mp4',true)).toThrow();expect(()=>cmsUrl('/a.m3u8',true)).toThrow()});
  it('accepts nested slugs and rejects empty/path traversal segments',()=>{expect(cmsSlug('Help/Windows')).toBe('help/windows');for(const slug of ['a//b','../a','/a','a/','a?x=1'])expect(()=>cmsSlug(slug)).toThrow()});
  it('allows incomplete drafts but validates each published content type',()=>{const draft=Object.assign(new CmsWriteDto(),{title:'新文章',slug:'draft',type:'ARTICLE',format:'MARKDOWN'});expect(normalizeCms(draft).body).toBe('');expect(()=>cmsSnapshot(draft,true)).toThrow();expect(()=>cmsSnapshot({...draft,body:'正文'},true)).not.toThrow();expect(()=>cmsSnapshot({...draft,type:'FAQ',faqQuestion:'问题',faqAnswer:''},true)).toThrow();expect(()=>cmsSnapshot({...draft,type:'FAQ',faqQuestion:'问题',faqAnswer:'答案'},true)).not.toThrow();expect(()=>cmsSnapshot({...draft,type:'VIDEO'},true)).toThrow();expect(()=>cmsSnapshot({...draft,type:'VIDEO',videoUrl:'https://example.com/a.m3u8'},true)).not.toThrow()});
  it('hashes only public snapshot fields and changes on public content changes',()=>{const row={title:'标题',body:'正文',format:'MARKDOWN',type:'ARTICLE'};expect(cmsSnapshot(row).hash).toBe(cmsSnapshot({...row,ragEnabled:true,viewCount:99}).hash);expect(cmsSnapshot(row).hash).not.toBe(cmsSnapshot({...row,body:'变更'}).hash)});
  it('handles 2000 levels iteratively and refuses self, descendant, missing or cross-scope parent',()=>{const nodes=Array.from({length:2000},(_,i)=>({id:String(i),parentId:i?String(i-1):null,scope:'CONTENT'}));expect(()=>validateCategoryParent(nodes,undefined,'1999','CONTENT')).not.toThrow();expect(descendantIds(nodes,'0')).toHaveLength(2000);for(const parent of ['0','1999','missing'])expect(()=>validateCategoryParent(nodes,'0',parent,'CONTENT')).toThrow();expect(()=>validateCategoryParent(nodes,undefined,'0','PRODUCT')).toThrow()});
});
