import { readFileSync } from 'node:fs';
const read = path => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const schema=read('apps/api/prisma/schema.prisma'),migration=read('apps/api/prisma/migrations/20260829070000_stage7_media_library/migration.sql');
const inspect=read('apps/api/src/media-file.ts'),storage=read('apps/api/src/media-storage.service.ts'),service=read('apps/api/src/media.service.ts'),controller=read('apps/api/src/media.controller.ts');
const manager=read('apps/web/src/components/MediaManager.vue'),picker=read('apps/web/src/components/MediaPicker.vue'),editor=read('apps/web/src/components/PageEditor.vue'),admin=read('apps/web/src/views/Admin.vue');
const compose=read('docker-compose.yml'),env=read('.env.example');
const seed=read('apps/api/prisma/seed.ts');
const failures=[];const required=(text,pattern,message)=>{if(!pattern.test(text))failures.push(message)};
required(schema,/model\s+MediaAsset\s*\{[\s\S]*?storageKey\s+String\s+@unique[\s\S]*?sha256[\s\S]*?archivedAt/,'缺少可校验、可归档的媒体资产模型');
required(migration,/MediaAsset_byte_size_check[\s\S]*?MediaAsset_mime_type_check[\s\S]*?MediaAsset_storage_key_check/,'媒体迁移缺少大小、类型或存储键数据库约束');
required(migration+seed,/system\.schemaVersion[\s\S]*?(?:'7'::jsonb|value:\s*7)/,'第七阶段未更新系统 Schema 版本');
required(inspect,/image\/jpeg[\s\S]*?image\/png[\s\S]*?image\/gif[\s\S]*?image\/webp/,'图片内容类型白名单不完整');
required(inspect,/MAX_MEDIA_PIXELS\s*=\s*40_000_000/,'图片缺少解压像素上限');
required(inspect,/buffer\.subarray\(0,\s*8\)[\s\S]*?jpegDimensions[\s\S]*?webpDimensions/,'图片未按真实字节签名和尺寸检查');
if(/image\/svg|\.svg/.test(inspect.match(/ALLOWED_IMAGE_MIME_TYPES[\s\S]*?as const/)?.[0]||''))failures.push('上传白名单错误允许 SVG');
required(storage,/filePath\(storageKey[\s\S]*?startsWith\(this\.baseDirectory\s*\+\s*sep\)/,'本地存储缺少路径越界保护');
required(storage,/open\(target,\s*'wx'[\s\S]*?file\.writeFile\(bytes\)[\s\S]*?file\.sync\(/,'媒体写入不是不可覆盖、落盘后创建');
required(storage,/isSymbolicLink\([\s\S]*?realpath\([\s\S]*?stat\.size > MAX_MEDIA_BYTES/,'媒体存储缺少符号链接或有界读取保护');
required(inspect,/animated:\s*true[\s\S]*?failOn:\s*'warning'[\s\S]*?\.raw\(\)\.toBuffer\(\)/,'上传未完整解码所有帧');
required(service,/await validateImage\(file\.buffer\)/,'上传服务没有使用完整解码校验');
required(service,/findUnique\(\{ where: \{ storageKey \} \}\)[\s\S]*?if \(!committed\) await this\.storage\.remove/,'事务失败后缺少独立确认，可能误删已提交文件');
required(service,/createHash\('sha256'\)[\s\S]*?MEDIA_UPLOADED/,'上传缺少哈希和审计');
required(service,/MEDIA_ARCHIVED[\s\S]*?storageRetained:\s*true[\s\S]*?MEDIA_RESTORED/,'媒体归档恢复边界不完整');
required(service,/媒体文件完整性校验失败/,'公开读取未复核文件完整性');
required(controller,/FileInterceptor\('file'[\s\S]*?fileSize:\s*MAX_MEDIA_BYTES[\s\S]*?files:\s*1/,'上传接口缺少文件数量或体积限制');
required(controller,/@Roles\('EDITOR',[\s\S]*?@Delete\(':id'\)[\s\S]*?@Roles\('ADMIN'/,'媒体写入和归档 RBAC 不完整');
required(controller,/X-Content-Type-Options':\s*'nosniff'[\s\S]*?Cross-Origin-Resource-Policy':\s*'cross-origin'/,'公开图片响应安全头不完整');
required(manager,/FormData[\s\S]*?\/admin\/media[\s\S]*?归档[\s\S]*?恢复/,'后台媒体库缺少上传、归档或恢复');
required(picker,/emit\('select'[\s\S]*?从媒体库选择图片/,'媒体选择器不完整');
required(editor,/MediaPicker[\s\S]*?从媒体库选择[\s\S]*?SEO 分享图/,'页面编辑器未接入媒体选择器');
required(admin,/\['media',\s*'媒体资源库'/,'后台主菜单缺少媒体库');
required(compose,/appgog_media:\/app\/data\/media[\s\S]*?appgog_media:/,'容器缺少持久媒体卷');
required(env,/MEDIA_STORAGE_DIR=data\/media/,'环境模板缺少媒体存储目录');
required(read('deploy/nginx.conf'),/client_max_body_size 11m/,'代理上传上限与后端 10 MiB 不匹配');
required(read('apps/web/src/media-client.ts'),/revision[\s\S]*?pageCount[\s\S]*?resolveMediaUrl/,'媒体客户端缺少分页或请求竞态保护');
required(read('apps/api/src/media.http.spec.ts'),/app\.listen\([\s\S]*?new FormData\([\s\S]*?toBe\(413\)/,'缺少真实 HTTP multipart/体积验证');
if(/XBOARD_(?:API|DB|DATABASE|SSO|SESSION|TOKEN|SECRET)|xboardUserId/i.test(inspect+storage+service+controller))failures.push('媒体模块违反 Xboard 完全隔离边界');
if(failures.length){console.error('APPGOG 媒体系统检查失败：\n'+failures.map(x=>`- ${x}`).join('\n'));process.exit(1)}
console.log('APPGOG 媒体系统检查通过：资产、内容嗅探、路径、完整性、RBAC、审计、归档、持久卷和编辑器接入完整。');
