<script setup lang="ts">
import {computed,onUnmounted,ref,watch} from 'vue';import {useRoute} from 'vue-router';
import {api} from '../../api';import type {Block} from '../../types';import ProductDetails from '../ProductDetails.vue';
import {canPurchase,externalPurchaseUrl,moneyLabel,type PublicProduct} from '../../catalog-client';import {useCatalogCart} from '../../catalog-cart';
const props=defineProps<{block:Block}>(),route=useRoute(),cart=useCatalogCart();
const {ids,items:cartItems,missing,loading:cartLoading,error:cartError,storageWarning,totals}=cart;
const rows=ref<PublicProduct[]>([]),loading=ref(false),error=ref(''),message=ref(''),page=ref(1),total=ref(0),detail=ref<string|null>(null);let generation=0;
const limit=computed(()=>Math.min(50,Math.max(1,Number(props.block.props.limit)||8))),columns=computed(()=>({'--catalog-cols':String(Math.min(4,Math.max(1,Number(props.block.props.columns)||4)))}));
async function load(){if(props.block.type!=='products')return;const request=++generation;loading.value=true;error.value='';try{const {data}=await api.get('/public/product-search',{params:{categoryId:typeof route.query.productCategory==='string'?route.query.productCategory:props.block.props.categoryId||undefined,sort:props.block.props.sort||'salesDesc',limit:limit.value,page:page.value}});if(request!==generation)return;rows.value=data.items;total.value=data.total;if(page.value>1&&!data.items.length){page.value=1;await load()}}catch{if(request===generation){rows.value=[];error.value='商品目录暂时无法加载，请重试'}}finally{if(request===generation)loading.value=false}}
function add(item:PublicProduct){message.value=cart.add(item)||'已加入独立购物车'}
async function turn(offset:number){page.value+=offset;await load()}
watch(()=>[props.block.type,JSON.stringify(props.block.props),route.query.productCategory],()=>{page.value=1;void load()},{immediate:true});onUnmounted(()=>{generation++});
</script>
<template><section class="block data-block catalog-block" :class="[`block-${block.type}`,`style-${block.props.cardStyle||'glass'}`,`hover-${block.props.hoverEffect||'lift'}`]">
<template v-if="block.type==='products'"><h2>{{block.props.title}}</h2><p v-if="loading" role="status">正在加载商品…</p><p v-else-if="error" role="alert">{{error}} <button @click="load">重试商品</button></p><div v-else-if="rows.length" class="catalog-grid" :style="columns"><article v-for="item in rows" :key="item.id"><img v-if="item.coverUrl" :src="item.coverUrl" :alt="item.name" loading="lazy"><h3>{{item.name}}</h3><p>{{item.summary}}</p><p><strong>{{moneyLabel(item.price,item.currency)}}</strong> <del v-if="item.compareAtPrice">{{moneyLabel(item.compareAtPrice,item.currency)}}</del></p><p>{{item.stock>0?`库存 ${item.stock}`:'已售罄'}} · 销量 {{item.sales}}</p><div class="catalog-actions"><button @click="detail=item.id">查看详情</button><button :disabled="!canPurchase(item)" @click="add(item)">加入购物车</button><a v-if="canPurchase(item)" :href="externalPurchaseUrl(item.externalUrl)" target="_blank" rel="noopener noreferrer">立即购买 ↗</a><span v-else>{{item.stock<=0?'已售罄':'暂不可购买'}}</span></div></article></div><p v-else>暂无商品</p><nav class="cms-pagination" aria-label="商品分页"><button :disabled="loading||page<=1" @click="turn(-1)">上一页</button><span>{{page}} / {{Math.max(1,Math.ceil(total/limit))}}</span><button :disabled="loading||page*limit>=total" @click="turn(1)">下一页</button></nav></template>
<aside v-else class="catalog-cart" :class="`catalog-cart-${block.props.position||'bottom-right'}`" aria-label="独立购物车"><h2>{{block.props.title}}（{{ids.length}}）</h2><p v-if="!ids.length">尚未添加商品</p><p v-if="cartLoading" role="status">正在核验最新商品信息…</p><p v-if="cartError" role="alert">{{cartError}}</p><p v-if="storageWarning" role="status">{{storageWarning}}</p><ul><li v-for="item in cartItems" :key="item.id"><button class="catalog-detail-link" @click="detail=item.id">{{item.name}}</button><span>{{moneyLabel(item.price,item.currency)}}</span><span v-if="!canPurchase(item)">{{item.stock<=0?'已售罄':'暂不可购买'}}</span><a v-if="!cartLoading&&!cartError&&canPurchase(item)" :href="externalPurchaseUrl(item.externalUrl)" target="_blank" rel="noopener noreferrer">前往外部购买 ↗</a><button :aria-label="`移除 ${item.name}`" @click="cart.remove(item.id)">移除</button></li><li v-for="id in missing" :key="id"><span>商品已下架或不存在</span><button :aria-label="`移除失效商品 ${id}`" @click="cart.remove(id)">移除</button></li></ul><p v-for="sum in (!cartLoading&&!cartError?totals:[])" :key="sum.currency">参考合计：{{sum.currency}} {{sum.amount}}</p><div class="catalog-actions"><button :disabled="cartLoading" @click="cart.refresh">刷新商品信息</button><button :disabled="!ids.length" @click="cart.clear">清空购物车</button></div><p class="catalog-note">每种商品收录一次，按币种分别汇总，不换汇。请逐项前往外站确认数量、结算和交付；不会在本站合并支付或预留库存。</p></aside>
<p v-if="message" role="status">{{message}}</p><ProductDetails :id="detail" @close="detail=null" @add="add" /></section></template>
